### ISSUE TITLE
Ensure no errors are thrown when unit conversion is passed by user

### ISSUE THREAD

**Issue by kaustubanand** [MintonGroup/swiftest#26]

**Comment by kaustubanand** [comment]
Going to add 'km' as a pre-defined unit as well.

What about letting the user pass a user-defined `MU` but `MU2KG` and other conversions take priority? 
The name is purely bookkeeping/robustness.

**Comment by profminton** [comment]
The user can already pass `MU_name` to make a custom name of their `MU2KG` unit (same with TU and DU)

**Comment by profminton** [comment]
`km` was added as part of #29
