### ISSUE TITLE
Ensure correct particle type is set when user-defined names have a smaller dtype

### ISSUE THREAD

**Issue by kaustubanand** [MintonGroup/swiftest#28]

**Comment by kaustubanand** [comment]
`xr.full_like()` (line 2764 in simulation.py) doesn't set the right particle type for test particles. Does not apply for massive or semi-interacting particles because `xr.where` doesn't need `dtype`.

For example, 
if particle name is 'tp_0' (dtype = U4), the size is smaller than the particle type 'Test Particle' (dtype = U13). As a result, the particle type is stored as 'Test' and the simulation crashes.
ex: name = 'tp_001' -> particle_type = 'Test P'

**Comment by profminton** [comment]
This has been fixed as part of  #29
