### ISSUE TITLE
Move 'Name' to a variable in collisions.nc

### ISSUE THREAD

**Issue by kaustubanand** [MintonGroup/swiftest#39]

**Comment by kaustubanand** [comment]
1. Remove `name` as a dimension/coordinate.

2. Make `num` a 1-D dimension-coordinate as a count of bodies involved in a collision. The length will be of the maximum number of bodies in a collision stage.
3. Add a new data variable for `name` of bodies involved in a particular collision:
`name` : variable with dimensions (`collision_id`, `stage`, `num`)
coords for the `num` dimension will be a count of just the bodies involved in that particular collision (`collision_id`). 

**Ex:** We have 2 collisions where `collision_id = 1` has 2 bodies before and 10 bodies after; `collision_id = 2` has 4 bodies before and 1 body after. 

Therefore `num` will be of length 10, `collision_id` is length 2, and `stage` is length 2.

For `sim.collisions['name'].values` has shape (2, 2, 10)
For `sim.collisions.sel(collision_id = 1, stage = 'before')['name'].values` has shape (10)

**Comment by kaustubanand** [comment]
`num` for a given collision can have coords `[1, 2, 3, .......]` but `name` can be `['body_1', 'body_2', ......., '', '']` (empty when bodies aren't involved).

**Comment by profminton** [comment]
This is done. l discovered a number of issues with the way collision information was being stored to `collisions.nc` that needed some extensive fixes.  The before/after energy states were not being computed properly, and not all collisions were being stored in the file. I added a new suite of tests, `test_collisions.py`, to ensure that the collision code is working.
